version: '3.9'

services:
  mysql_db:
    container_name: mysql_db
    cap_add:
      - SYS_NICE
    build:
      context: ./db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'springuser'
      MYSQL_PASSWORD: 'springpass'
      MYSQL_ROOT_PASSWORD: 'root'
    restart: on-failure
    networks:
      - gateway

  app:
    container_name: app
    build:
      context: ./api
      args:
        PROFILE: prod
    ports:
      - '8888:8888'
    restart: on-failure
    links:
      - mysql_db
    depends_on:
      - mysql_db
    networks:
      - gateway

  client:
    container_name: client
    build:
      context: ./client
    ports:
      - '80:80'
    restart: on-failure
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    links:
      - app
    depends_on:
      - app
    networks:
      - gateway

networks:
  gateway: {}
