version: '3.9'

services:
  mysql_db_sec:
    container_name: mysql_db_sec
    cap_add:
      - SYS_NICE
    build:
      context: ./db
    ports:
      - '3306:3306'
    env_file: ./.env
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: on-failure
    networks:
      - gateway

  app_sec:
    container_name: app_sec
    env_file: ./.env
    build:
      context: ./api
      args:
        PROFILE: prod
        DATASOURCE_USERNAME: ${MYSQL_USERNAME}
        DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '8888:8888'
    restart: on-failure
    links:
      - mysql_db_sec
    depends_on:
      - mysql_db_sec
    networks:
      - gateway

  client_sec:
    container_name: client_sec
    build:
      context: ./client
    ports:
      - '80:80'
    restart: on-failure
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    links:
      - app_sec
    depends_on:
      - app_sec
    networks:
      - gateway

networks:
  gateway: {}
